apiVersion: v1
data:
  core-site.xml: |2-
        <configuration>
            <property>
                <name>fs.s3a.connection.ssl.enabled</name>
            <value>false</value>
            </property>
           <property>
                <name>fs.s3a.endpoint</name>
                <value>http://10.244.1.10:9000</value>
            </property>
            <property>
                <name>fs.s3a.fast.upload</name>
                <value>true</value>
            </property>
            <property>
                <name>fs.s3a.access.key</name>
                <value>minio</value>
            </property>
            <property>
                <name>fs.s3a.secret.key</name>
                <value>minio123</value>
            </property>
        </configuration>
  metastore-site.xml: |2-
     <configuration>
            <property>
                <name>metastore.task.threads.always</name>
                <value>org.apache.hadoop.hive.metastore.events.EventCleanerTask</value>
            </property>
            <property>
                <name>metastore.expression.proxy</name>
                <value>org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy</value>
            </property>
            <property>
                <name>javax.jdo.option.ConnectionURL</name>
                <value>jdbc:postgresql://mypostgres:5432/metadata?allowPublicKeyRetrieval=true&amp;useSSL=false&amp;serverTimezone=UTC</value>
            </property>
            <property>
                <name>javax.jdo.option.ConnectionDriverName</name>
                <value>org.postgresql.Driver</value>
            </property>
            <property>
                <name>javax.jdo.option.ConnectionUserName</name>
                <value>postgres</value>
            </property>
            <property>
                <name>javax.jdo.option.ConnectionPassword</name>
                <value>postgresSuperUserPsw</value>
            </property>
            <property>
                <name>metastore.warehouse.dir</name>
                <value>s3a://test/warehouse</value>
            </property>
            <property>
                <name>metastore.thrift.port</name>
                <value>9083</value>
            </property>
            <property>
                <name>metastore.log4j.file</name>
                <value>/opt/metastore-log4j2.properties</value>
            </property>
        </configuration>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: metastore-cfg
